#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
# Important for running: (1) You need a POSIX-compliant shell to run this script.

# Attempt to set APP_HOME
app_path=$0

# Resolve links
while [ -h "$app_path" ]; do
    APP_HOME=$(dirname "$app_path")
    cd "$APP_HOME"
    app_path=$(readlink "$app_path")
    cd - >/dev/null
done

APP_BASE_NAME=$(basename "$0")
APP_HOME=$(dirname "$app_path")

# Use the maximum available file descriptors
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*" >&2
    echo
    exit 1
} >&2

# OS specific support
cygwin=false
darwin=false
case "$(uname)" in
  CYGWIN* ) cygwin=true  ;;
  Darwin* ) darwin=true  ;;
esac

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

detect_java_executable() {
  if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
  elif type -p java >/dev/null 2>&1; then
    JAVACMD=java
  else
    die "ERROR: JAVA_HOME is not set and no java command could be found in your PATH."
  fi
}

if [ -n "$JAVA_HOME" ]; then
  detect_java_executable
fi

# Set the working directory to the project directory
cd "$APP_HOME"

# Setup the command line
CMD_LINE="$JAVACMD -Dorg.gradle.appname=$APP_BASE_NAME -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain"

# Execute the command
eval "$CMD_LINE "$@""
